# Generated by Django 5.1.4 on 2025-04-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options_remove_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="property_images/details/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Mô tả ngắn về hình ảnh (tốt cho SEO và người dùng khiếm thị)",
                        max_length=255,
                        null=True,
                        verbose_name="Văn bản thay thế",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tải lên"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Bất động sản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh chi tiết BĐS",
                "verbose_name_plural": "Ảnh chi tiết BĐS",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
