# Generated by Django 5.1.4 on 2025-04-25 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="users_wishlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="wishlist_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng quan tâm",
            ),
        ),
    ]
